### ISSUE TITLE
Deploying Error

### ISSUE THREAD

**Issue by slavakurilyak** [snipcart/stackbit-theme-planty#10]
I'm having an issue deploying stackbit-theme-planty theme using Stackbit.

I tried to deploy using Jekyll and Gatsby as site generators. I also tried Sanity and Forestry as CMS with no success.

Here is the Sanity log for deploying stackbit-theme-planty using Gatsby, Sanity, Github, Netlify:

```
Error building project:
Stackbit Factory Build Error: received an error while uploading models and content:
{ ClientError: Bad Request - Invalid image, could not read metadata
    at onResponse (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/@sanity/client/lib/http/request.js:27:13)
    at middleware.(anonymous function).reduce (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/get-it/lib-node/util/middlewareReducer.js:10:22)
    at Array.reduce (<anonymous>)
    at applyMiddleware (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/get-it/lib-node/util/middlewareReducer.js:9:29)
    at onResponse (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/get-it/lib-node/index.js:81:22)
    at httpRequest (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/get-it/lib-node/index.js:48:55)
    at callback (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/get-it/lib-node/request/node-request.js:57:46)
    at concat (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/get-it/lib-node/request/node-request.js:141:14)
    at DestroyableTransform.<anonymous> (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/simple-concat/index.js:7:13)
    at Object.onceWrapper (events.js:286:20)
  response:
   { body:
      { statusCode: 400,
        error: 'Bad Request',
        message: 'Invalid image, could not read metadata',
        details:
         'webp2vips: unable to read pixels\nVipsRegion: valid clipped to nothing\nVipsRegion: valid clipped to nothing\nVipsRegion: valid clipped to nothing\nVipsRegion: valid clipped to nothing\nVipsRegion: valid clipped to nothing\nVipsRegion: valid clipped to nothing\nVipsRegion: valid clipped to nothing\n' },
     url:
      'https://gfd6xtoc.api.sanity.io/v1/assets/images/production?filename=plant1-lg.webp',
     method: 'POST',
     headers:
      { 'content-type': 'application/json; charset=utf-8',
        'content-length': '404',
        etag: 'W/"194-1YEqI9K8Ow7pHuFoxhwPHmKIqUs"',
        date: 'Thu, 12 Mar 2020 21:18:55 GMT',
        vary: 'Origin',
        via: '1.1 google',
        'alt-svc': 'clear',
        connection: 'close' },
     statusCode: 400,
     statusMessage: 'Bad Request' },
  statusCode: 400,
  responseBody:
   '{\n  "statusCode": 400,\n  "error": "Bad Request",\n  "message": "Invalid image, could not read metadata",\n  "details": "webp2vips: unable to read pixels\\nVipsRegion: valid clipped to nothing\\nVipsRegion: valid clipped to nothing\\nVipsRegion: valid clipped to nothing\\nVipsRegion: valid clipped to nothing\\nVipsRegion: valid clipped to nothing\\nVipsRegion: valid clipped to nothing\\nVipsRegion: valid clipped to nothing\\n"\n}' }
{ ClientError: Bad Request - Invalid image, could not read metadata
    at onResponse (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/@sanity/client/lib/http/request.js:27:13)
    at middleware.(anonymous function).reduce (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/get-it/lib-node/util/middlewareReducer.js:10:22)
    at Array.reduce (<anonymous>)
    at applyMiddleware (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/get-it/lib-node/util/middlewareReducer.js:9:29)
    at onResponse (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/get-it/lib-node/index.js:81:22)
    at httpRequest (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/get-it/lib-node/index.js:48:55)
    at callback (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/get-it/lib-node/request/node-request.js:57:46)
    at concat (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/get-it/lib-node/request/node-request.js:141:14)
    at DestroyableTransform.<anonymous> (/usr/src/app/data/stackbit-factory/v0.2.82/node_modules/simple-concat/index.js:7:13)
    at Object.onceWrapper (events.js:286:20)
  response:
   { body:
      { statusCode: 400,
        error: 'Bad Request',
        message: 'Invalid image, could not read metadata',
        details:
         'webp2vips: unable to read pixels\nVipsRegion: valid clipped to nothing\nVipsRegion: valid clipped to nothing\nVipsRegion: valid clipped to nothing\nVipsRegion: valid clipped to nothing\nVipsRegion: valid clipped to nothing\nVipsRegion: valid clipped to nothing\nVipsRegion: valid clipped to nothing\n' },
     url:
      'https://gfd6xtoc.api.sanity.io/v1/assets/images/production?filename=plant1-lg.webp',
     method: 'POST',
     headers:
      { 'content-type': 'application/json; charset=utf-8',
        'content-length': '404',
        etag: 'W/"194-1YEqI9K8Ow7pHuFoxhwPHmKIqUs"',
        date: 'Thu, 12 Mar 2020 21:18:55 GMT',
        vary: 'Origin',
        via: '1.1 google',
        'alt-svc': 'clear',
        connection: 'close' },
     statusCode: 400,
     statusMessage: 'Bad Request' },
  statusCode: 400,
  responseBody:
   '{\n  "statusCode": 400,\n  "error": "Bad Request",\n  "message": "Invalid image, could not read metadata",\n  "details": "webp2vips: unable to read pixels\\nVipsRegion: valid clipped to nothing\\nVipsRegion: valid clipped to nothing\\nVipsRegion: valid clipped to nothing\\nVipsRegion: valid clipped to nothing\\nVipsRegion: valid clipped to nothing\\nVipsRegion: valid clipped to nothing\\nVipsRegion: valid clipped to nothing\\n"\n}' }
```

Here is the Netlify log for deploying stackbit-theme-planty using Gatsby, Forestry, Github, Netlify:

```
2:34:13 PM: Build ready to start
2:34:15 PM: build-image version: 2dbd444fcdce00cf06325060a8238d5ae3e86774
2:34:15 PM: build-image tag: v3.3.7
2:34:15 PM: buildbot version: 11918e084194721d200458438c92ff8180b3b56c
2:34:16 PM: Fetching cached dependencies
2:34:16 PM: Failed to fetch cache, continuing with build
2:34:16 PM: Starting to prepare the repo for build
2:34:16 PM: No cached dependencies found. Cloning fresh repo
2:34:16 PM: git clone git@github.com:slavakurilyak/great-olive
2:34:18 PM: Preparing Git Reference refs/heads/master
2:34:18 PM: Found Netlify configuration file netlify.toml in site root
2:34:18 PM: Found Netlify configuration file(s). Overriding site configuration
2:34:18 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'public' versus '/' in the Netlify UI
2:34:18 PM: Different build command detected, going to use the one specified in the Netlify configuration file: './stackbit-build.sh' versus '' in the Netlify UI
2:34:18 PM: Starting build script
2:34:18 PM: Installing dependencies
2:34:20 PM: v10.19.0 is already installed.
2:34:20 PM: Now using node v10.19.0 (npm v6.13.4)
2:34:20 PM: Attempting ruby version 2.6.2, read from environment
2:34:22 PM: Using ruby version 2.6.2
2:34:22 PM: Using PHP version 5.6
2:34:22 PM: Started restoring cached node modules
2:34:22 PM: Finished restoring cached node modules
2:34:22 PM: Installing NPM modules using NPM version 6.13.4
2:34:49 PM: > node-sass@4.12.0 install /opt/build/repo/node_modules/node-sass
2:34:49 PM: > node scripts/install.js
2:34:49 PM: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-64_binding.node
2:34:50 PM: Download complete
2:34:50 PM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-64/binding.node
2:34:50 PM: Caching binary to /opt/buildhome/.npm/node-sass/4.12.0/linux-x64-64_binding.node
2:34:50 PM: > core-js@2.6.9 postinstall /opt/build/repo/node_modules/core-js
2:34:50 PM: > node scripts/postinstall || echo "ignore"
2:34:50 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
2:34:50 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
2:34:50 PM: > https://opencollective.com/core-js 
2:34:50 PM: > https://www.patreon.com/zloirock 
2:34:50 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
2:34:50 PM: > core-js-pure@3.1.4 postinstall /opt/build/repo/node_modules/core-js-pure
2:34:50 PM: > node scripts/postinstall || echo "ignore"
2:34:50 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
2:34:50 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
2:34:50 PM: > https://opencollective.com/core-js 
2:34:50 PM: > https://www.patreon.com/zloirock 
2:34:50 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
2:34:50 PM: > gatsby-telemetry@1.1.4 postinstall /opt/build/repo/node_modules/gatsby-telemetry
2:34:50 PM: > node src/postinstall.js
2:34:50 PM: > node-sass@4.12.0 postinstall /opt/build/repo/node_modules/node-sass
2:34:50 PM: > node scripts/build.js
2:34:51 PM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-64/binding.node
2:34:51 PM: Testing binary
2:34:51 PM: Binary is fine
2:34:53 PM: npm
2:34:53 PM: WARN snipcart@0.0.1 No repository field.
2:34:53 PM: npm
2:34:53 PM: WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
2:34:53 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2:34:53 PM: added 1709 packages from 889 contributors and audited 23575 packages in 29.513s
2:34:54 PM: found 1271 vulnerabilities (710 low, 6 moderate, 554 high, 1 critical)
2:34:54 PM:   run `npm audit fix` to fix them, or `npm audit` for details
2:34:54 PM: NPM modules installed
2:34:55 PM: Started restoring cached go cache
2:34:55 PM: Finished restoring cached go cache
2:34:55 PM: unset GOOS;
2:34:55 PM: unset GOARCH;
2:34:55 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
2:34:55 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
2:34:55 PM: go version >&2;
2:34:55 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
2:34:55 PM: go version go1.12 linux/amd64
2:34:55 PM: Installing missing commands
2:34:55 PM: Verify run directory
2:34:55 PM: Executing user command: ./stackbit-build.sh
2:34:55 PM: curl -s -X POST https://api.stackbit.com/project/5e6aa927d732be00148e08d8/webhook/build/pull > /dev/null
2:34:55 PM: if [[ -z "${STACKBIT_API_KEY}" ]]; then
2:34:55 PM:     echo "WARNING: No STACKBIT_API_KEY environment variable set, skipping stackbit-pull"
2:34:55 PM: else
2:34:55 PM:     npx @stackbit/stackbit-pull --stackbit-pull-api-url=https://api.stackbit.com/pull/5e6aa927d732be00148e08d8
2:34:55 PM: fi
2:34:57 PM: npx: installed 11 in 1.739s
2:34:57 PM: fetching data for project from https://api.stackbit.com/pull/5e6aa927d732be00148e08d8
2:34:58 PM: curl -s -X POST https://api.stackbit.com/project/5e6aa927d732be00148e08d8/webhook/build/ssgbuild > /dev/null
2:34:58 PM: gatsby build
2:35:01 PM: success open and validate gatsby-configs — 0.011
2:35:01 PM: success load plugins — 0.574
2:35:01 PM: success onPreInit — 0.005
2:35:01 PM: success delete html and css files from previous builds — 0.005
2:35:01 PM: success initialize cache — 0.032
2:35:01 PM: success copy gatsby files — 0.028
2:35:01 PM: success onPreBootstrap — 0.008
2:35:01 PM: success source and transform nodes — 0.109
2:35:02 PM: success building schema — 0.258
2:35:02 PM: success createPages — 0.125
2:35:02 PM: success createPagesStatefully — 0.032
2:35:02 PM: success onPreExtractQueries — 0.010
2:35:02 PM: success update schema — 0.144
2:35:02 PM: success extract queries from components — 0.025
2:35:02 PM: success run static queries — 0.001
2:35:02 PM: success run page queries — 0.025 — 17/17 718.64 queries/second
2:35:02 PM: success write out page data — 0.004
2:35:02 PM: success write out redirect data — 0.000
2:35:02 PM: success onPostBootstrap — 0.032
2:35:02 PM: info bootstrap finished - 3.826 s
2:35:02 PM: Browserslist: caniuse-lite is outdated. Please run next command `npm update`
2:35:18 PM: success Building production JavaScript and CSS bundles — 16.288
2:35:20 PM: error ReferenceError: _ is not defined
2:35:20 PM: Building static HTML failed for path "/about/"
2:35:20 PM: See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html ReferenceError: _ is not defined
2:35:20 PM: See our docs page for more info on this error: https://gatsby.dev/issue-how-to
2:35:20 PM:   17 |         <React.Fragment>
2:35:20 PM:   18 |             <script src={safePrefix('js/main.js')}/>
2:35:20 PM: > 19 |             <script src={_.get(this.props, 'pageContext.site.siteMetadata.snipcart_js')} defer/>
2:35:20 PM:      |                           ^
2:35:20 PM:   20 |             <div hidden id="snipcart" data-api-key={_.get(this.props, 'pageContext.site.siteMetadata.snipcart_api_key')}>
2:35:20 PM:   21 |               <cart-header title="Planty">
2:35:20 PM:   22 |                 <div className="root">
2:35:20 PM: 
2:35:20 PM:   WebpackError: ReferenceError: _ is not defined
2:35:20 PM:   
2:35:20 PM:   - gatsby-ssr.js:19 Object../gatsby-ssr.js.exports.onRenderBody
2:35:20 PM:     gatsby-ssr.js:19:27
2:35:20 PM:   
2:35:20 PM: 
2:35:20 PM: Skipping functions preparation step: no functions directory set
2:35:20 PM: Caching artifacts
2:35:20 PM: Started saving node modules
2:35:21 PM: Finished saving node modules
2:35:21 PM: Started saving pip cache
2:35:21 PM: Finished saving pip cache
2:35:21 PM: Started saving emacs cask dependencies
2:35:21 PM: Finished saving emacs cask dependencies
2:35:21 PM: Started saving maven dependencies
2:35:21 PM: Finished saving maven dependencies
2:35:21 PM: Started saving boot dependencies
2:35:21 PM: Finished saving boot dependencies
2:35:21 PM: Started saving go dependencies
2:35:21 PM: Finished saving go dependencies
2:35:23 PM: Error running command: Build script returned non-zero exit code: 1
2:35:23 PM: Failing build: Failed to build site
2:35:24 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
2:35:24 PM: Finished processing build request in 1m8.781304028s
```

Please advise.

**Comment by RoneelV** [comment]
> 2:35:20 PM:   WebpackError: ReferenceError: _ is not defined

Yeah that's what happened when I tried with Netlify CMS, I'm hoping to figure out myself why that happens.
Also see readme
> For the moment, this theme works only with Jekyll but will soon work with other static site generators supported by Stackbit.

Also see comments [here](https://snipcart.com/blog/stackbit#disqus_thread)

**Comment by RoneelV** [comment]
> 2:35:20 PM:   WebpackError: ReferenceError: _ is not defined

I got solution for that.
```javascript
const _ = require("lodash");
```
Add this line in gatsby-ssr.js in root directory of GitHub repo **after** Unibit has done its magic.

Not sure whether this is mistake from Unibit or the theme.

**Comment by slavakurilyak** [comment]
Lodash is a [dependency of Unibit](https://www.npmjs.com/package/@stackbit/unibit?activeTab=dependencies). Unibit uses lodash's [Nunjucks Filters](https://docs.stackbit.com/unibit/nunjucks-filters/) (orderBy, slice, split, startsWith, endsWith).

**Comment by RoneelV** [comment]
> Lodash is a dependency of Unibit. Unibit uses lodash's Nunjucks Filters.

Yeah, I know that. Are you suggesting this is mistake on part of Unibit? Maybe it is. 
For now, adding require solves the error for me for Gatsby + Netlify CMS. I hope it works for you, too.

**Comment by MikeFarrow** [comment]
Thanks Roneel
